### ISSUE TITLE
Supporting gzip input?

### ISSUE THREAD

**Issue by shenwei356** [Rbfinch/grepq#1]
Most of the time, FASTQ files are compressed in gzip format. So it would be better for `grepq` to seamlessly read plain or gzip (or other formats) compression format.

I've compared `grepq` with [seqkit grep -s -P](https://bioinf.shenwei.me/seqkit/usage/#grep), `grepq` is 2x faster.

**Comment by Rbfinch** [comment]
Thanks for the suggested Wei Shen.  I've now implemented gzip support.
BTW, your tools are great!

Thanks again,
Nick Crosbie
